### ISSUE TITLE
BUG: 1.2.5 每夜版闪退

### ISSUE THREAD

**Issue by HydrangeaPurple** [AntiNeko/CatBoxForAndroid#18]
## 描述问题

预期行为：

实际行为：
部分节点显示emoji都错乱了，随后闪退，再次打开变成了日志分享界面

## 如何复现
录屏：https://pixeldrain.com/u/rLK87wyn

## 日志
https://pixeldrain.com/u/e6ZWbMDr

**Comment by xchacha20-poly1305** [comment]
我也复现了，感觉有效的日志是：

```
 [Error] [CrashHandler] Thread[DefaultDispatcher-worker-1 @coroutine#53,5,main]
 [Error] [CrashHandler] java.lang.StringIndexOutOfBoundsException: length=43; regionStart=0; regionLength=-1093171156
 at java.lang.StringFactory.newStringFromChars(StringFactory.java:110)
 at com.esotericsoftware.kryo.io.ByteBufferInput.readString(ByteBufferInput.java:719)
 at io.nekohasekai.sagernet.fmt.AbstractBean.deserializeFromBuffer(AbstractBean.java:99)
 at io.nekohasekai.sagernet.fmt.KryoConverters.deserialize(KryoConverters.java:52)
 at io.nekohasekai.sagernet.fmt.KryoConverters.vmessDeserialize(KryoConverters.java:87)
 at io.nekohasekai.sagernet.database.ProxyEntity_Dao_Impl.getByGroup(ProxyEntity_Dao_Impl.java:788)
 at io.nekohasekai.sagernet.ui.ConfigurationFragment$GroupFragment$ConfigurationAdapter.reloadProfiles(ConfigurationFragment.kt:1381)
 at io.nekohasekai.sagernet.ui.ConfigurationFragment$GroupFragment$onResume$2.invokeSuspend(ConfigurationFragment.kt:1054)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
 Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineId(53), "coroutine#53":StandaloneCoroutine{Cancelling}@3b9b904, Dispatchers.Default]
```

**Comment by xchacha20-poly1305** [comment]
https://github.com/AntiNeko/CatBoxForAndroid/releases/tag/1.2.6

1.2.6 已发布，应该修好了。

**Comment by HydrangeaPurple** [comment]
> https://github.com/AntiNeko/CatBoxForAndroid/releases/tag/1.2.6
> 
> 1.2.6 已发布，应该修好了。

okkk
